// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.PortalkahveCustomer", b =>
                {
                    b.Property<int>("PortalkahveCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("PortalkahveCustomerBirtdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PortalkahveCustomerIdentityNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("PortalkahveCustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortalkahveCustomerSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortalkahveCustomerId");

                    b.ToTable("PortalkahveCustomers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SturbucksCustomer", b =>
                {
                    b.Property<int>("SturbucksCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("SturbucksCustomerBirtdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SturbucksCustomerIdentityNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("SturbucksCustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SturbucksCustomerSurname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SturbucksCustomerId");

                    b.ToTable("SturbucksCustomers");
                });
#pragma warning restore 612, 618
        }
    }
}
